### ISSUE TITLE
Fails at bundle install

### ISSUE THREAD

**Issue by hdamico** [avmnu-sng/rspec-tracer#12]
## Expected behavior

Using the last version of SimpleCov (0.21.2) I should be able to do `bundle install` successfully.

## Actual behavior

It fails because SimpleCov depends on `docile ~> 1.1` and `rspec-tracer` on `docile ~> 1.1.0`.

## Steps to reproduce the problem

Add the last version of SimpleCov and rspec-tracer on the gemfile.

## 0.2.0

Include **Ruby**, **RSpecTracer**, and **RSpec** version. Also include
**Simplecov** version if applicable.

**Comment by avmnu-sng** [comment]
@hdamico what's the ruby version you're using? Can you share the output of the `bundle install`?

**Comment by avmnu-sng** [comment]
@hdamico It should work now with `v0.3.0`
